variable "aws_region" { type = string }
# variable "aws_region_2" { type = string }
variable "amis" { type = map(any) }
variable "vpc_cidr" { type = string }
variable "vpc_name" { type = string }
variable "key_name" { type = string }
variable "public-Subnet-cidrs" { type = list(any) }
variable "private-Subnet-cidrs" { type = list(any) }
variable "azs" { type = list(any) }
variable "environment" { type = string }
variable "instance_type" { type = map(any) }
variable "projectId" { type = string }
variable "imagename" { type = string }